import { test } from '@playwright/test';

// Story as admin

test('Story as admin', async ({ page }) => {
  await page.goto('http://localhost:5173/login');
  await page.locator('input[type="text"]').click();
  await page.locator('input[type="text"]').fill('admin');
  await page.locator('input[type="password"]').click();
  await page.locator('input[type="password"]').fill('zaq12wsx');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByRole('link', { name: 'Projects' }).click();
  await page.getByRole('link', { name: 'Add Project' }).click();
  await page.locator('input[type="text"]').click();
  await page.locator('input[type="text"]').fill('Projectt');
  await page.locator('textarea').click();
  await page.locator('textarea').fill('test');
  await page.getByRole('button', { name: 'Add project' }).click();
  await page.getByRole('button', { name: 'Set as Active' }).click();
  await page.getByRole('button', { name: 'Add Story' }).click();
  await page.locator('input[type="text"]').click();
  await page.locator('input[type="text"]').fill('StoryTest1');
  await page.locator('textarea').click();
  await page.locator('textarea').fill('test');
  await page.getByRole('button', { name: 'Add story' }).click();
  await page.getByRole('button', { name: 'Add Story' }).click();
  await page.locator('input[type="text"]').click();
  await page.locator('input[type="text"]').fill('StoryTest2');
  await page.locator('textarea').click();
  await page.locator('textarea').fill('test');
  await page.getByLabel('Priority:').selectOption('medium');
  await page.getByLabel('Status:').selectOption('doing');
  await page.getByRole('button', { name: 'Add story' }).click();
  await page.getByRole('link', { name: 'Edit' }).first().click();
  await page.getByLabel('Status:').selectOption('done');
  await page.locator('input[type="text"]').click();
  await page.locator('input[type="text"]').fill('StoryTest1t');
  await page.locator('input[type="text"]').fill('StoryTest1');
  await page.getByRole('button', { name: 'Edit story' }).click();
  await page.getByLabel('Filter by status:').selectOption('todo');
  await page.getByLabel('Filter by status:').selectOption('doing');
  await page.getByText('Filter by status:nonetododoingdone').click();
  await page.getByLabel('Filter by status:').selectOption('done');
  await page.getByRole('button', { name: 'Delete' }).click();
  await page.getByRole('button', { name: 'Delete' }).click();
  await page.getByLabel('Filter by status:').selectOption('none');
  await page.goto('http://localhost:5173/projects');
  await page.getByRole('button', { name: 'Change active project !' }).click();
  await page.getByRole('button', { name: 'Delete' }).click();
  await page.close();
});